#####################################################
############## General data parameters ##############
#####################################################

# data_dir: "/Users/samdeblank/Documents/1.projects/tcell_paper/unprocessed/2021-06-10_WT1_n1/1.data/"
output_dir: "/Users/samdeblank/surfdrive/Shared/T cell paper/Revision_nature_biotech/Sam_analysis/ror1_cart_combined/1.analysis"
metadata_csv_path: "/Users/samdeblank/surfdrive/Shared/T cell paper/Revision_nature_biotech/Sam_analysis/ror1_cart_combined/ror1_cart_combined_metadata.txt"

# Channel information
# organoid_channel: 3
dead_dye_channel: 3
dist_org_channel: 8

# Track metadata
#From CD4_CD8_4_6_hours_beh_import.R line 159

#####################################################
### Parameters for T-cell dynamics classification ###
#####################################################

randomforest_path: "/Users/samdeblank/OneDrive - Prinses Maxima Centrum/github/BEHAV3D-forked/references/TrainedRandomForest.Rdata"
reference_map_path: "/Users/samdeblank/OneDrive - Prinses Maxima Centrum/github/BEHAV3D-forked/references/Behavioral_Referance_map_git"

# Maximum length of experiment (all timepoints after will be cut)
exp_duration: 300
# Maximum track length to take into analysis. Cut longer tracks to the length defined below
max_track_length: 100
# Nearest distance for Tcell contact
tcell_contact_thr: 10

# Intensity cut-off to define dead T-cells
dead_tcell_thr: 10

# # Take cells interacting at specific timepoint - CD4_CD8_4_6_hours_beh_import.R line 162
# incubation_selection: 155
# # Select only cells with track-length longer than min_track_length (in timepoints) - CD4_CD8_4_6_hours_beh_import.R line 162
# min_track_length: 59
# # max_track_length:
# # Nr. of timepoints to take from the end of a cells track - CD4_CD8_4_6_hours_beh_import.R line 173
# track_length_cutoff: 100
